### PR TITLE
fix deploy not failing with critical option

### PR DESCRIPTION
**Pull request by eredi93**
right now the deploy fails only if the request library throw an error eg: Timeouts, bad SSL certs etc.
with this change it also fials the deploy if the response code is not 2xx

### CODE REVIEW

**Comment by eredi93** [comment]
added the tests, let me know if you think i need to change something else

**Comment by marcoow** [comment]
@LevelbossMike: can you have a look as well?

**Comment by eredi93** [comment]
@LevelbossMike @marcoow any update on this?

**Comment by LevelbossMike** [comment]
Sorry for taking so long. Overlooked this pr

**Comment by eredi93** [comment]
thank you. can you do a patch release too?

**Pull request merged**
